### ISSUE TITLE
Consider loading map javascript automatically

### ISSUE THREAD

**Issue by antony** [peopledrivemecrazy/here-maps-svelte#1]
Hey! Just been pointed to this library by a friend, and it looks great.

I wondered if you knew about / were interested in loading the third party javascript automatically. See https://github.com/beyonk-adventures/svelte-mapbox/blob/master/src/Map.svelte#L92

I recently added support for loading multiple js files in one shot. Might be a nice way to make your library easier/quicker to get up and running!

**Comment by peopledrivemecrazy** [comment]
This looks great I will try this

**Comment by evdama** [comment]
> This looks great I will try this

Is there any progress on this? I like this package a lot since HERE maps are more or less the market leader, and combining this package with smartystreets API lookups for address verification makes for a great overal dev experience and great results 👍

**Comment by peopledrivemecrazy** [comment]
I had stashed this project aside, Now I have added @antony async-loader into the source itself, I did get on here-dev slack and there is `https://js.api.here.com/v3/3.1/mapsjs.bundle.js` for the entire bundle. 

@evdama Really sorry I couldn't look into this 


The head scripts in the `index.html` are no longer required 🚀 

`npm i here-maps-svelte@latest` should fetch the `0.0.7`
